# Generated by Django 3.1.8 on 2021-04-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='associate_contract',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='term_of_contract',
            field=models.CharField(blank=True, choices=[('이용허락', 'FIRST')], max_length=300, null=True),
        ),
    ]
