# Generated by Django 3.1.8 on 2021-04-11 12:15

import config.utils
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_auto_20210411_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='term',
        ),
        migrations.AddField(
            model_name='contract',
            name='end_term',
            field=models.DateTimeField(default=config.utils.two_hour_hence),
        ),
        migrations.AddField(
            model_name='contract',
            name='start_term',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
